replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/microservices-test-ps/java-app/weather-service
  tag: "v1.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /weather
          pathType: Prefix
  tls: []  # Configure if using HTTPS

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
