replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/microservices-test-ps/python-app/fortune-teller
  tag: v1.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

livenessProbe:
  path: /
  initialDelaySeconds: 40
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  path: /
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
