pipeline {
    agent any

    parameters {
    string(name: 'PROJECT_ID', defaultValue: 'microservices-test-ps', description: 'GCP project ID')
    string(name: 'GKE_CLUSTER', defaultValue: '', description: 'Cluster name')
    string(name: 'REGION', defaultValue: '', description: 'Region where cluster is located')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Git Checkout') {
            steps {
                git branch: 'main', changelog: false, credentialsId: 'github-token', poll: false, url: 'https://github.com/fastest-man-alive/microservices-test.git'
            }
        }

        stage('Authenticate to GKE Cluster') {
            steps {
                sh '''
                    gcloud container clusters get-credentials $GKE_CLUSTER --region $region --project $PROJECT_ID
                '''
            }
        }

        stage('Get Cluster Details') {
            steps {
                sh '''
                    cd automation
                    python3 test.py
                '''
            }
        }
    }
}